### ISSUE TITLE
Y24-295 - [BUG] Exception 29/08/2024 at 09:47

### ISSUE THREAD

**Issue by wendyyang** [sanger/limber#1887] opened 2024-09-03 14:59 UTC
**Email subject line**
[Psd-exceptions] [Limber PRODUCTION] search#create (ActionController::RespondToMismatchError) "respond_to was called multiple times and m...

**Error body**
```
An ActionController::RespondToMismatchError occurred in search#create:

  respond_to was called multiple times and matched with conflicting formats in this action. Please note that you may only call respond_to and match on a single format per action.
  app/controllers/search_controller.rb:46:in `rescue in create'

```
**Acceptance Criteria**
- [ ] Look into this exception and fix the code to handle the exception sensibly.
- [ ]  Document the root cause and solution in a comment on this issue.

**Additional information**
The id of the user who triggered this error is often shown in the exception email, in case you need to communicate with them.

**Comment by stevieing** [comment] 2024-10-09 07:56
Closed as duplicate of #1887

**Closed by stevieing** 2024-10-09 07:56 UTC
