### ISSUE TITLE
DPL-314 [BUG] 404 when Limber tries to draw 50x error pages

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#1020] opened 2022-03-08 14:04 UTC
**Describe the bug**
When attempting to render 500 errors Limber looks for a file specifically called 50x.html instead of interpreting the x as the relevant number. e.g.
`FATAL -- :  ActionController::RoutingError (No route matches [GET] "/50x.html"):`
This results in an unhelpful 404 error page instead.

**RT Ticket Number**
NA

**To Reproduce**
N.B. This was observed in UAT during the day Openstack was regarded 'at risk', so may not be easy to replicate
Steps to reproduce the behaviour:
1. Go to the page for a Heron LTHR-384 Lib PCR pool plate
2. Click on button to Add an empty LTHR-384 PCR XP tube
3. Enter a PhiX tube barcode and click create
4. Creation was very slow, but did work, but the error was observed when attempting to render the plate page (and children tab) again. Some kind of time out?

**Expected behaviour**
Render the 500 error page

**Screenshots**
just see a 404 useless error screen

**Additional context**
James thinks the x in the URL should have been interpreted automatically, so possibly an update broke something.

**Comment by JamesGlover** [comment] 2022-03-08 17:52
Duplicate of https://github.com/sanger/deployment/issues/45

**Comment by KatyTaylor** [comment] 2022-03-09 15:07
Closing as is duplicate (linked in previous comment)

**Closed by KatyTaylor** 2022-03-09 15:07 UTC
Labels: bug
